# Generated by Django 4.0 on 2021-12-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='highlighted',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
