# Generated by Django 4.0 on 2021-12-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_song_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='highlighted',
        ),
    ]
